package jabratech:component-active-instruments;

world component-active-instruments {
    import wasi:logging/logging;
    import jabratech:component-agg-ticker/agg-ticker;

    export wasi:http/incoming-handler@0.2.0;
}